{
 "title": "OpenVSX proxy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(up{job=\"openvsx-proxy\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Cache Hits",
   "type": "timeseries",
   "description": "The percentage of responses that can be served from the backup cache on an upstream outage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(gitpod_openvsx_proxy_backup_cache_hit_total{pod=~\"$pod\"}[5m])) / (sum(rate(gitpod_openvsx_proxy_backup_cache_hit_total{pod=~\"$pod\"}[5m])) + sum(rate(gitpod_openvsx_proxy_backup_cache_miss_total{pod=~\"$pod\"}[5m])))",
     "legendFormat": "backup cache hits"
    }
   ]
  },
  {
   "title": "Regular Cache Hits",
   "type": "timeseries",
   "description": "The percentage of served responses from the regular cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(gitpod_openvsx_proxy_regular_cache_hit_and_serve_total{pod=~\"$pod\"}[5m])) / (sum(rate(gitpod_openvsx_proxy_regular_cache_hit_and_serve_total{pod=~\"$pod\"}[5m])) + sum(rate(gitpod_openvsx_proxy_regular_cache_miss_total{pod=~\"$pod\"}[5m])))",
     "legendFormat": "regular cache hits"
    }
   ]
  },
  {
   "title": "Served Responses from the Backups Cache",
   "type": "timeseries",
   "description": "The number/percentage of responses that are actually served from the backup cache due to an upstream outage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(gitpod_openvsx_proxy_backup_cache_serve_total{pod=~\"$pod\"}[5m]))",
     "legendFormat": "Served Backups"
    }
   ]
  },
  {
   "title": "Duration Overall Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_bucket{pod=~\"$pod\"}[5m])) by (le))",
     "legendFormat": "100%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_bucket{pod=~\"$pod\"}[5m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_bucket{pod=~\"$pod\"}[5m])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_bucket{pod=~\"$pod\"}[5m])) by (le))",
     "legendFormat": "80%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(gitpod_openvsx_proxy_duration_overall_seconds_bucket{pod=~\"$pod\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Number of requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(gitpod_openvsx_proxy_duration_overall_seconds_count{pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(gitpod_openvsx_proxy_requests_total{pod=~\"$pod\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}